### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by sfeilmeier** [OpenEMS/openems-gui#10]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

Enable translations of the application. See https://angular.io/docs/ts/latest/cookbook/i18n.html for details.

**Comment by sfeilmeier** [comment]
Translation of strings in code is not supported at the moment.
See https://github.com/angular/angular/issues/11405
Possible workaround: https://github.com/angular/angular/issues/11405#issuecomment-295151768

**Comment by lisakaindl** [comment]
maybe try this tutorial:
http://blog.danieleghidoli.it/2017/01/15/i18n-angular-cli-aot/#

**Comment by sfeilmeier** [comment]
German tutorial in Heise:
https://www.heise.de/developer/artikel/Internationalisierung-mit-Angular-Bordmitteln-3703621.html#mobile_detect_force_desktop

**Comment by sfeilmeier** [comment]
Second part of the tutorial at Heise:
https://www.heise.de/developer/artikel/Internationalisierung-fuer-Angular-Teil-2-ngx-translate-3722374.html?wt_ref=https%253A%252F%252Fwww.google.com%252F&wt_t=1495666349133
