### ISSUE TITLE
Invalid session

### ISSUE THREAD

**Issue by sfeilmeier** [OpenEMS/openems-gui#12]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

If the Odoo session is not anymore valid, there is only a small message and no more notification.

### Desired functionality.

Forward user to www.fenecon.de login screen. Also set "redirect" variable to redirect him again after successful login.

**Comment by ebakir** [comment]
[https://github.com/OpenEMS/openems-gui/commit/3724ca868e90c027ec5320c36befb1569cd95571](url)
