### ISSUE TITLE
Show spinner while waiting for data

### ISSUE THREAD

**Issue by sfeilmeier** [OpenEMS/openems-gui#24]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

The user should receive some feedback, that the ui is waiting for data. Currently the charts are just not shown at all. Instead they should show a spinner.

**Comment by ebakir** [comment]
trying with this one
https://www.npmjs.com/package/angular-spinners
