### ISSUE TITLE
Improve Websocket handling

### ISSUE THREAD

**Issue by sfeilmeier** [OpenEMS/openems-gui#6]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
Currently, if the websocket connection closes, the user is redirected to the login screen and loosing all the information he entered till then. 

Instead a message should be shown, that the connection was lost and the system should try to reconnect automatically.

Areas that are not able anymore to update automatically, should show a waiting spinner.

**Comment by ebakir** [comment]
https://github.com/OpenEMS/openems-gui/commit/32f15c8ce02c54170a7ed6a23bf487c9dfc64ba3
