### ISSUE TITLE
History data for all devices

### ISSUE THREAD

**Issue by MatthiasRossmann** [OpenEMS/openems-gui#8]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
show activePower of all meter,ess,... in the history graphs

**Comment by sfeilmeier** [comment]
Also evaluate the usage of Influxdb continuous queries with fill(previous)
https://docs.influxdata.com/influxdb/v1.2/query_language/continuous_queries/

**Comment by sfeilmeier** [comment]
Right now no historic data is shown e.g. for fems380 (https://fenecon.de/m/device/fenecon.de/fems380/overview). Seems to be connected with https://github.com/OpenEMS/femsserver/issues/1.
